pipeline:
  identifier: Build_adithya10_12ramesh_intern_1750330022384
  name: Build intern
  orgIdentifier: default
  projectIdentifier: intern
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1750330006102
        repoName: adithya10-12ramesh/intern
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install --upgrade pip

                      # Remove cloud-init as it's not available on PyPI
                      if [ -f requirements.txt ]; then
                        echo "Original requirements.txt:"
                        cat requirements.txt
                        
                        # Remove cloud-init from requirements
                        grep -v "cloud-init" requirements.txt > requirements_no_cloud_init.txt
                        
                        echo "Modified requirements (without cloud-init):"
                        cat requirements_no_cloud_init.txt
                        
                        # Install dependencies without cloud-init
                        python3 -m pip install -r requirements_no_cloud_init.txt
                      else
                        echo "No requirements.txt found"
                      fi

                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      . .venv/bin/activate
                      python3 -m pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
